# Generated by Django 5.1.1 on 2025-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
