# Generated by Django 5.1.1 on 2025-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('shawarma', 'Shawarma'), ('shawarma_plate', 'Shawarma Plate'), ('loaded_shawarma', 'Loaded Shawarma'), ('combos_for_one', 'Combos for One'), ('combos_for_two', 'Combos for Two'), ('healthy_shawarma', 'Healthy Shawarma'), ('only_for_cheese_lovers', 'Only for Cheese Lovers'), ('add_on', 'Add-On')], default='starter', max_length=100)),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Starter',
        ),
    ]
