# Generated by Django 5.1.1 on 2025-02-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_menuitems_delete_starter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombosForOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombosForTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthyShawarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadedShawarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnlyForCheeseLovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shawarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShawarmaPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=500)),
                ('sub_items_name', models.CharField(max_length=2000)),
                ('half_price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
    ]
