name: Django CI/CD with Docker

on:
  push:
    branches:
      - main  # Adjust this if your branch name is different

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DATABASE_NAME: defaultdb
          DATABASE_USER: avnadmin
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: simpleeshawarmadb-shawarmadb.l.aivencloud.com
          DATABASE_PORT: 16038
          DJANGO_SETTINGS_MODULE: Simplee.settings
        run: |
          python manage.py test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Change to your preferred region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t simpleeshawarma:latest .

      - name: Push Docker Image to ECR
        run: |
          docker tag simpleeshawarma:latest ${{ steps.login-ecr.outputs.registry }}/simpleeshawarma:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/simpleeshawarma:latest