# name: Django CI/CD with Docker

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-and-build:
#     runs-on: ubuntu-latest

#     # services:
#     #   postgres:
#     #     image: postgres:13
#     #     env:
#     #       POSTGRES_USER: django
#     #       POSTGRES_PASSWORD: django
#     #       POSTGRES_DB: test_db
#     #     ports:
#     #       - 5432:5432

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run Django Tests
#         env:
#           DATABASE_URL: postgres://django:django@localhost:5432/test_db
#         run: |
#           python manage.py test

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker Image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/django-docker:latest .

#       - name: Push Docker Image
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/django-docker:latest

#       # - name: Deploy to Server
#       #   if: success()
#       #   run: |
#       #     ssh user@yourserver "docker pull ${{ secrets.DOCKER_USERNAME }}/django-docker:latest && docker-compose up -d"




name: Django CI/CD with Docker

on:
  push:
    branches:
      - new-branch  # Adjust this if your branch name is different

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: Simplee.settings
        run: |
          python manage.py test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Change to your preferred region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t simpleeshawarma:latest .

      - name: Push Docker Image to ECR
        run: |
          docker tag simpleeshawarma:latest ${{ steps.login-ecr.outputs.registry }}/simpleeshawarma:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/simpleeshawarma:latest