name: Django CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create .env file
        run: |
          echo "DATABASE_NAME=defaultdb" >> .env
          echo "DATABASE_USER=avnadmin" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=simpleeshawarmadb-shawarmadb.l.aivencloud.com" >> .env
          echo "DATABASE_PORT=16038" >> .env

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        env:
          DATABASE_NAME: defaultdb
          DATABASE_USER: avnadmin
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: simpleeshawarmadb-shawarmadb.l.aivencloud.com
          DATABASE_PORT: 16038
          DJANGO_SETTINGS_MODULE: Simplee.settings
        run: python manage.py test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        env:
          DATABASE_NAME: defaultdb
          DATABASE_USER: avnadmin
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: simpleeshawarmadb-shawarmadb.l.aivencloud.com
          DATABASE_PORT: 16038
        run: |
          docker-compose build
          docker tag simpleeshawarma:latest ${{ steps.login-ecr.outputs.registry }}/simpleeshawarma:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/simpleeshawarma:latest
